### ISSUE TITLE
Conflict with Android O

### ISSUE THREAD

**Issue by sandeeprana011** [smart-fun/SmartFonts#6]
Can't compile source code
``` ~ /mobile/build/intermediates/res/merged/debug/values/values.xml
Error:(1144) Attribute "font" already defined with incompatible format.
Error:(1006) Original attribute defined here.
Error:(1144) Attribute "font" already defined with incompatible format.
Error:(1006) Original attribute defined here.
Error:Execution failed for task ':mobile:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

**Comment by smart-fun** [comment]
Hello,

yes Android 8 introduced fonts in XML. I have to handle the name conflict. If you are targeting Android 8 you can use the new Android 8 feature:
https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml.html

I tell you when the new version of SmartFonts is available.

Arnaud.

**Comment by smart-fun** [comment]
@sandeeprana011 a version 1.0.3 has been released. The font attribute is now "smart_font".
